# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-10-05 19:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course_metadata', '0062_courserun_license'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subject',
            name='description',
        ),
        migrations.RemoveField(
            model_name='subject',
            name='name',
        ),
        migrations.RemoveField(
            model_name='subject',
            name='subtitle',
        ),
        migrations.AddField(
            model_name='subjecttranslation',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='subjecttranslation',
            name='name',
            field=models.CharField(default='TODO', max_length=255),
        ),
        migrations.AddField(
            model_name='subjecttranslation',
            name='subtitle',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
