# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-10-13 20:16
from __future__ import unicode_literals

from django.db import migrations, models
import django_extensions.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('course_metadata', '0064_migrate_subjecttranslations_data'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subjecttranslation',
            name='description_t',
        ),
        migrations.RemoveField(
            model_name='subjecttranslation',
            name='name_t',
        ),
        migrations.RemoveField(
            model_name='subjecttranslation',
            name='subtitle_t',
        ),
        migrations.AlterField(
            model_name='subject',
            name='slug',
            field=django_extensions.db.fields.AutoSlugField(blank=True, editable=False, help_text='Leave this field blank to have the value generated automatically.', populate_from='name'),
        ),
        migrations.AlterField(
            model_name='subjecttranslation',
            name='name',
            field=models.CharField(max_length=255),
        ),
    ]
